server:
  port: 6789

spring:
  jackson:
    serialization:
      order-map-entries-by-keys: true
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

keycloak:
  client_id: evcsa
  client_secret: FSvY3TYoK1wmJEBknoq8KrfdTXiGT1dP  #DO NOT PUT THIS ON PROD! GIVE IT VIA ENV OR READ FROM CONFIG SERVER
  grant_type_password: password
  grant_type_refresh_token: refresh_token
  admin_login_url: "http://localhost:8890/realms/master/protocol/openid-connect/token"
  register_url: http://localhost:8890/admin/realms/master/users
  login_url: http://localhost:8890/realms/master/protocol/openid-connect/token

