server:
  port: 6789


spring:
  jackson:
    serialization:
      order-map-entries-by-keys: true
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  application:
    name: AUTH-SERVICE

  rabbitmq:
    username: rabbitmq
    password: 123456
    ssl:
      enabled: false
    listener:
      simple:
        default-requeue-rejected: false
      direct:
        retry:
          enabled: true
        acknowledge-mode: auto
    host: localhost
    port: 5672

keycloak:
  client_id: evcsa
  client_secret: yUAIJMBP5ZeykbypTXinudvAhwszmovd  #DO NOT PUT THIS ON PROD! GIVE IT VIA ENV OR READ FROM CONFIG SERVER
  grant_type_password: password
  grant_type_refresh_token: refresh_token
  admin_login_url: "http://localhost:8890/realms/master/protocol/openid-connect/token"
  register_url: http://localhost:8890/admin/realms/master/users
  login_url: http://localhost:8890/realms/master/protocol/openid-connect/token

rabbitconfig:
  user_registration_queue: user-registration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8152/eureka
    instance:
      preferIpAddress: true

