server:
  servlet:
    context-path: /ev-data
  port: 6790

keycloak:
  realm: master
  auth-server-url: http://localhost:8890
  ssl-required: external
  bearer-only: true
  public-client: true
  resource: evcsa

spring:
  application:
    name: EV-DATA-SERVICE
  data:
    mongodb:
      database: evdata
      uri: mongodb://localhost:27017
  jackson:
    serialization:
      order-map-entries-by-keys: true
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration